#!/bin/bash

new() {
	echo "Building UNet..."
	python ./models/unet.py $*
}

train () {
	echo "Training UNet from directory"
	python ./utils/train.py $*
}

test() {
	echo "Test"
}

predict() {
	echo "Predict"
}


to_run=$1
case $to_run in
	
	new) new ${@:2};;

	train) train ${@:2};;

	test) test ;;

	predict) predict ;;

esac
